/*
 * 配置服务API
 * 配置服务API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xopenapi.config.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BatchRetrieveByResourcesReq
 */
public class BatchRetrieveByResourcesReqTest {
    private final BatchRetrieveByResourcesReq model = new BatchRetrieveByResourcesReq();

    /**
     * Model tests for BatchRetrieveByResourcesReq
     */
    @Test
    public void testBatchRetrieveByResourcesReq() {
        // TODO: test BatchRetrieveByResourcesReq
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'resourceIds'
     */
    @Test
    public void resourceIdsTest() {
        // TODO: test resourceIds
    }

}
