/*
 * 配置服务API
 * 配置服务API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xopenapi.config.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BatchRetrieveConfigTemplateByKeysReq
 */
public class BatchRetrieveConfigTemplateByKeysReqTest {
    private final BatchRetrieveConfigTemplateByKeysReq model = new BatchRetrieveConfigTemplateByKeysReq();

    /**
     * Model tests for BatchRetrieveConfigTemplateByKeysReq
     */
    @Test
    public void testBatchRetrieveConfigTemplateByKeysReq() {
        // TODO: test BatchRetrieveConfigTemplateByKeysReq
    }

    /**
     * Test the property 'keys'
     */
    @Test
    public void keysTest() {
        // TODO: test keys
    }

}
