/*
 * 配置服务API
 * 配置服务API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xopenapi.config.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SortSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-08T10:50:47.636Z[GMT]")
public class SortSpec {
  public static final String SERIALIZED_NAME_PROPERTY = "property";
  @SerializedName(SERIALIZED_NAME_PROPERTY)
  private String property;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_IGNORE_CASE = "ignoreCase";
  @SerializedName(SERIALIZED_NAME_IGNORE_CASE)
  private String ignoreCase;


  public SortSpec property(String property) {
    
    this.property = property;
    return this;
  }

   /**
   * 排序字段
   * @return property
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "排序字段")

  public String getProperty() {
    return property;
  }


  public void setProperty(String property) {
    this.property = property;
  }


  public SortSpec type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * 排序类型，0默认，1升序，2降序
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "排序类型，0默认，1升序，2降序")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public SortSpec ignoreCase(String ignoreCase) {
    
    this.ignoreCase = ignoreCase;
    return this;
  }

   /**
   * 是否忽略大小写
   * @return ignoreCase
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "是否忽略大小写")

  public String getIgnoreCase() {
    return ignoreCase;
  }


  public void setIgnoreCase(String ignoreCase) {
    this.ignoreCase = ignoreCase;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SortSpec sortSpec = (SortSpec) o;
    return Objects.equals(this.property, sortSpec.property) &&
        Objects.equals(this.type, sortSpec.type) &&
        Objects.equals(this.ignoreCase, sortSpec.ignoreCase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(property, type, ignoreCase);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SortSpec {\n");
    sb.append("    property: ").append(toIndentedString(property)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    ignoreCase: ").append(toIndentedString(ignoreCase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

